database:
  host: postgres
  port: 5432
  database: witnzdb
  user: witnz
  password: witnz_dev_password

hash:
  algorithm: sha256

node:
  id: node1
  bind_addr: node1:7000
  data_dir: /data
  bootstrap: true
  peer_addrs:
    node2: node2:7000
    node3: node3:7000

protected_tables:
  - name: audit_log
    verify_interval: 30s

alerts:
  enabled: true
